### ISSUE TITLE
It is planned to modify the @ path module and add @ requestparam and requestfile to support the following usage scenarios. Welcome to the discussion.

### ISSUE THREAD

**Issue by dazjean** [wuba/Umajs#27]
从规范上来说，后端人员需要友好地标准方法支持的请求类型。但`@Path`装饰器修饰方法时，如果不指定method，默认支持GET,POST,PUT,OPTION等所有的请求类型。为了更方便开发者使用@Path装饰器，计划对@Path模块进行修改，新增@RequestParam,RequestFile以支持以下使用场景。欢迎大家参与讨论

## 简写@Path指定Method方式
当需要指定某个方法特定的请求类型时，可以通过`@umajs/path`提供的 GET,POST等装饰器直接修饰方法。框架默认Path则需要通过@Path({value,method})创建，为了更方便使用创建简写方式。
```
@Path('/home',RequestMethod.GET)
index(){

}
```

## `@Path`默认处理controller方法
在controller中，可以指定URL默认的处理方法
```
@Path('/home')
export default class Home extend BaseControoler {
    @Path()  
    index() {
        return Result.send(`This is a default Handler Method`);
    }
}
```
当`/home`请求发送时，`index()`方法会作为处理方法，因为`@Path`没有传递任何值.

## `@RequestParam`不指定method时默认请求参数处理
当使用`@Path('/home') `或者`@Path({value:"/home'})`时，请求`/home`默认支持所有类型的请求处理。那么query和Body中的参数如何接收呢？我们可以通过`@RequestParam`修饰器获取query或者body请求体中的参数。

- 获取特定参数
```
@Path('/home')
home(@RequestParam('id') id:string) {
        return Result.send(`This router RequestParms is ${id}`);
}
```

- 获取多个参数自定义实体对象
```
type User = {
    age:number,
    userName:string
}

@Path('/home')
home(@RequestParam(['age','userName']) user:User) {
        return Result.send(`The age is ${user.age}. userName is ${user.userName}`);
}
```

- 获取完整请求参数对象
当使用`@RequestParam()` 修饰参数时，参数将获取到所有接受到的参数并由框架封装成对象。
```
@Path('/home')
home(@RequestParam() user:any) {
        return Result.send(`The RequestParam is ${JSON.stringfy(user)}`);
}
```

## @RequestFile处理文件上传
```
@Path('/uploadwos',RequestMethod.POST)
uploadFile(@RequestFile('file') wosFile:File){
    let { name, size, path } = wosFile;
    // TODO 
}

```

**Comment by EdwardZZZ** [comment]
>简写@path指定Method方式
>@Path('/home',RequestMethod.GET)
这个有 Post、Get 装饰器了 参考`@umajs/path`，而且 这个实现需要再判断且不优雅。

>@Path默认处理controller方法
计划在 V2 版本中取消默认路由，正在讨论之中

> RequestParam、RequestFile
建议不错，可以添加

**Comment by dazjean** [comment]
And other problems have when the request URL end with / . It's returned 404 not found.
eg：
```
@Path('/home')
home() {
        return Result.send(`hello Umajs!`);
}
```
 request `/home` will get right result,but `/home/` will be get 404

it will be resolved by next version.

**Comment by EdwardZZZ** [comment]
> And other problems have when the request URL end with / . It's returned 404 not found.
> eg：
> 
> ```
> @Path('/home')
> home() {
>         return Result.send(`hello Umajs!`);
> }
> ```
> 
> request `/home` will get right result,but `/home/` will be get 404
> 
> it will be resolved by next version.

Done by umajs@1.1.3

**Comment by dazjean** [comment]
# @Body参数修饰器建议默认集成到core模块提供。
默认core期望提供的参数修饰器如下：
- @Query(key:string)   【GET请求】
- @Body(key:string || string[]) 【POST请求】
- @Param(key:string) 【ALL,请求中的param】
- @RequestParam(key:string || string[])  【ALL , 当Path不指定请求类型时，可兼容获取GET，POST，参数获取顺序：POST<GET】

# @umajs/arg-decorator 参数，校验装饰器新增
-  @Headers(key:string) 【不支持参数校验】
-  @Cookies(key:string) 【不支持参数校验】

**Comment by EdwardZZZ** [comment]
> # @Body参数修饰器建议默认集成到core模块提供。
> 默认core期望提供的参数修饰器如下：
> 
> * @query(key:string)   【GET请求】
> * @Body(key:string || string[]) 【POST请求】
> * @param(key:string) 【ALL,请求中的param】
> * @RequestParam(key:string || string[])  【ALL , 当Path不指定请求类型时，可兼容获取GET，POST，参数获取顺序：POST<GET】
> 
> # @umajs/arg-decorator 参数，校验装饰器新增
> * @headers(key:string) 【不支持参数校验】
> * @Cookies(key:string) 【不支持参数校验】

Body 参数装饰器是基于 koa-body，而框架不是强制使用 koa-body，所以不建议内置在 core 中。
Headers、Cookies 可以添加。

**Comment by dazjean** [comment]
> > # @Body参数修饰器建议默认集成到core模块提供。
> > 默认core期望提供的参数修饰器如下：
> > 
> > * @query(key:string)   【GET请求】
> > * @Body(key:string || string[]) 【POST请求】
> > * @param(key:string) 【ALL,请求中的param】
> > * @RequestParam(key:string || string[])  【ALL , 当Path不指定请求类型时，可兼容获取GET，POST，参数获取顺序：POST<GET】
> > 
> > # @umajs/arg-decorator 参数，校验装饰器新增
> > 
> > * @headers(key:string) 【不支持参数校验】
> > * @Cookies(key:string) 【不支持参数校验】
> 
> Body 参数装饰器是基于 koa-body，而框架不是强制使用 koa-body，所以不建议内置在 core 中。
> Headers、Cookies 可以添加。

@Path默认ALL类型 那么当被默认当做POST请求时框架还需要进行koa-body依赖提醒。框架不默认依赖koa-body是基于什么考虑呢？

**Comment by EdwardZZZ** [comment]
> > > # @Body参数修饰器建议默认集成到core模块提供。
> @path默认ALL类型 那么当被默认当做POST请求时框架还需要进行koa-body依赖提醒。框架不默认依赖koa-body是基于什么考虑呢？

koa-body 是默认依赖的，但是可以配置成其它库。这么做的目的有两个：
1、可选让用户有更多选择
2、core 做的更轻量
