### ISSUE TITLE
Sample项目貌似无法运行

### ISSUE THREAD

**Issue by yibingxiong** [wuba/Umajs#34]
**Describe the bug**
根据readme, cd packages/app && npm run app. 发现无法运行，装了依赖包也没法运行

**To Reproduce**
1. cd packages
2. yarn
3. npm run app

![image](https://user-images.githubusercontent.com/20298674/100587037-0971df00-332b-11eb-9bf2-725f5f99b2b6.png)

**Expected behavior**
能够正常运行Sample

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dazjean** [comment]
npm run init  初始化一下lerna工程配置 不用单独cd到app目录安装依赖

**Comment by dazjean** [comment]
> **Describe the bug**
> 根据readme, cd packages/app && npm run app. 发现无法运行，装了依赖包也没法运行
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. cd packages
> 2. yarn
> 3. npm run app
> 
> ![image](https://user-images.githubusercontent.com/20298674/100587037-0971df00-332b-11eb-9bf2-725f5f99b2b6.png)
> 
> **Expected behavior**
> 能够正常运行Sample
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

npm run init 初始化一下lerna工程配置 不用单独cd到app目录安装依赖
