### ISSUE TITLE
https://umajs.github.io/ 打不开

### ISSUE THREAD

**Issue by ssszp** [wuba/Umajs#36]
如题，应该为 [ https://umajs.gitee.io/ ] ？

**Comment by dazjean** [comment]
> 如题，应该为 [ https://umajs.gitee.io/ ] ？

根据国内网络现状，github受到到访问限制。Umajs官方推荐使用文档为：[https://umajs.gitee.io/](https://umajs.gitee.io/)。但同时我们也会及时同步[https://umajs.github.io/](https://umajs.github.io/)。

**Comment by ssszp** [comment]
那建议把readme中的链接替换一下😃

**Comment by dazjean** [comment]
> 那建议把readme中的链接替换一下😃

感谢反馈~~  已更新。
