### ISSUE TITLE
@Path() not surpport when  used by controller on class

### ISSUE THREAD

**Issue by dazjean** [wuba/Umajs#39]
**Describe the bug**
I want to be in index.controller.ts The default website route is set in the file, and multiple route defaults need to be set. But get the error information of the framework.
eg:`http://localhost:8001/`  `http://localhost:8001/index`

```
@Path()   // umajs not surport @Path() set defualt home Page; report a bugs
@Path('/index')
export default class Index extends BaseController {
    @Path()
    index(){
    }
}

```

**Comment by dazjean** [comment]
Usually, @ path ('/') is set as the default route, but the path decorator allows @ path() to be used when decorating method methods. So let's see if the same usage method of class is supported.

**Comment by EdwardZZZ** [comment]
> Usually, @ path ('/') is set as the default route, but the path decorator allows @ path() to be used when decorating method methods. So let's see if the same usage method of class is supported.

Emm... When @Path() decorator method means this method is class default method...
```
// @Path()  It doesn't make sense
@Path('/test')
class {
    @Path()  // this method url is '/test'
    index() {}
}
```
